### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': function (dispatch)

### ISSUE THREAD

**Issue by vincegerald** [AOHUA/redux-state-sync#53]
This error will trigger once I access datas in my redux. 
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': function (dispatch)

**Comment by AOHUA** [comment]
https://github.com/AOHUA/redux-state-sync/issues/49#issuecomment-570147813 please refer to this issue, I will give more meaningful error message for this when I got time. Thanks.

**Comment by vincegerald** [comment]
@AOHUA  much appreciated! But what are the common causes of this?

**Comment by aschenkel** [comment]
@AOHUA @vincegerald it seems to be caused by redux-persist `persist/PERSIST` action

the error is gone when adding it to the blacklist.

```javascript
createStateSyncMiddleware({
    blacklist: ['persist/PERSIST'],
  })
```

---
but then this error appears, which at least seems to be nicer.

<img width="639" alt="Screen Shot 2020-03-03 at 11 51 05" src="https://user-images.githubusercontent.com/25759182/75787790-0028f700-5d46-11ea-9db5-1c882a105ed5.png">

despite having 

```javascript
 const persistConfig = {
    ...
    blacklist: ['_persist'],
  }
```

**Comment by AOHUA** [comment]
This issue is most probably caused by non-serializable data in the store. Not sure if it is caused by misuse of redux-persist. I will try to replicate the issue with redux-persist when I got some time.

**Comment by aschenkel** [comment]
[Here](https://github.com/aschenkel/react-redux-persist-example) is a basic redux-persist example to which I added this package.

The error on the console is there.
I've hosted it [here](https://60d9ceff.ngrok.io) for today for u to see it without the need to run it locally.

The error is still happening no matter if the `rootReducer` is first wrapped with `persistReducer` or `withReduxStateSync`

**Comment by AOHUA** [comment]
Thanks @aschenkel appreciate that. but the site is no longer available. I will try to find sometime during the weekend to reproduce the issue.

**Comment by AOHUA** [comment]
I found the issue, there is an easy solution to remove the error, however, I'm not sure if this will cause any other issues. I hope it helps.

```
import { PERSIST } from 'redux-persist/es/constants';

const persistedReducer = persistReducer(persistConfig, rootReducer);

const middlewares = [
    // disable PERSIST action.
    createStateSyncMiddleware({
        blacklist: [PERSIST],
    }),
];
const store = createStore(persistedReducer, {}, applyMiddleware(...middlewares));

const persistor = persistStore(store);
``` 

https://github.com/rt2zz/redux-persist/blob/d7efde9115a0bd2d6a0309ac6fb1c018bf06dc30/src/persistStore.js#L120

Seems that redux-persist is dispatching a function when persisting the state.

**Comment by AOHUA** [comment]
@aschenkel Actually it's not breaking the persist functionality, it only stops sending this persist function to other tabs which make sense in such case. Thank you for your help.

**Comment by AOHUA** [comment]
It actually makes sense to prevent all the redux-persist action in redux-state-sync

**Comment by AOHUA** [comment]
@vincegerald If it solves your problem, please close this issue. Thanks

**Comment by aschenkel** [comment]
@AOHUA that works.

I also have included the `PURGE` action to the blacklist, since on some cases was also generating the error.

```javascript
import { PERSIST, PURGE } from 'redux-persist/es/constants';

const middlewares = [
    createStateSyncMiddleware({
        blacklist: [PERSIST, PURGE],
    }),
];
```

**Comment by leopucci** [comment]
I´m having the same issue using axios and redux-thunk. 
so instead of a serializable object (with the nested type parameter that you can use to filter). 
I have a function being sent, with several lines of code. 
I think that should be wise to filter by type 

![image](https://user-images.githubusercontent.com/38509299/128726056-b6a80902-d6d1-4f35-8467-2d87c96f36ac.png)


```
// Function filter
if (typeof v === 'function') {
    // do something
}
```

**Comment by leopucci** [comment]
Solved with predicate use.

```
const reduxStateSyncConfig = {
  predicate: (action) => {
    const blacklist = [PERSIST, PURGE, REHYDRATE];
    if (typeof action !== "function") {
      if (Array.isArray(blacklist)) {
        return blacklist.indexOf(action.type) < 0;
      }
    }
    return false;
  },
};
```

**Comment by jhking17** [comment]
@leopucci Thank you for your help! It is worked for me!

My environment is redux with redux-persist, redux-thunk. 😄

**Comment by leopucci** [comment]
Anytime!

**Comment by mansiteharia123** [comment]
I am still facing this issue.

Chrome Version: 107.0.5304.107
"redux-persist": "^6.0.0",
